server:
  port: 8081
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest